version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  streamer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamer
    depends_on:
      - rabbitmq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      ENDPOINT: http://your-geyser-endpoint:9547
      TOKEN: your_token_here
    restart: on-failure
